name: CI Testing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 23.11.0
      - run: npm ci
      - run: npm run express-backend lint
      - run: npm run react-frontend lint
      - run: npm run react-frontend build
